package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.28

import (
	"context"

	"github.com/tokizuoh/eki-server/graph/model"
)

// Station is the resolver for the station field.
func (r *queryResolver) Station(ctx context.Context, name string) ([]*model.Station, error) {
	return r.station(name)
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
