// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Station struct {
	DetabaseID string `json:"detabaseID"`
	Name       string `json:"name"`
	IsLiked    bool   `json:"isLiked"`
}
